### ISSUE TITLE
Add examples

### ISSUE THREAD

**Issue by nkh** [LensPlaysGames/markdown2tex#1]
Hi, could you put some examples, specially of a multi-page markdow, if you support that, as well as how to generate the info files.

**Comment by LensPlaysGames** [comment]
I forgot I even made this, lol.

Did you read the README? On first glance it does have instructions and examples 👀

**Comment by nkh** [comment]
Yes, sometimes we forget what we do, lol 

I just got for me to document seriously https://github.com/nkh/P5-App-Asciio, a program I almost forgot I wrote but that got energized lately. I've decided to use mdbook because it's fluffy and nice for users but I'm a hardcore terminal person.  I've always disliked info (the tool) but I discovered a vim plugin that makes it almost nice to be in info file.

If I squint a bit I see the example but I think that a bit of hand holding, specially for a multiple mk doc, you may find other users more happy (yes it sometimes sucks to write docs).

I' probably lost 3 hours this week trying to find something that would be palatable, to no end. And don't get me started with the viewers, except konqueror and vim there's nothing really good and even those have a terrible UX.

**Comment by nkh** [comment]
Ah, yes there in the anchor section! I'll try it and if you wan to I may come back with some feedback about the doc.
